export default [
  {id:1, lastname:"MAGNUS",name:""},
  {id:2, lastname:"MAHENTA",name:" la Bernarde"},
  {id:3, lastname:"MAKOLINUS",name:" de Caryneors"},
  {id:4, lastname:"MALTILDIS",name:""},
  {id:5, lastname:"MAMMETUS",name:" Galie"},
  {id:6, lastname:"MANFREDUS",name:" Lumbardus"},
  {id:7, lastname:"MANG",name:" Steyner"},
  {id:8, lastname:"MANINNUS",name:" de Janua"},
  {id:9, lastname:"MARCELLUS",name:""},
  {id:10, lastname:"MARCIARDUS",name:""},
  {id:11, lastname:"MARCUS",name:" de Cernay"},
  {id:12, lastname:"MARCUS",name:" LEO de Mantoue"},
  {id:13, lastname:"MARCUS",name:" Leschere"},
  {id:14, lastname:"MARCUS",name:" de Mediolano"},
  {id:15, lastname:"MARCUS",name:" Travers"},
  {id:16, lastname:"MARCUS",name:" de Valle"},
  {id:17, lastname:"MARCVARDUS",name:" de Zayense"},
  {id:18, lastname:"MARGARETA ",name:"dou Celier"},
  {id:19, lastname:"MARGARETA",name:" la Choquette"},
  {id:20, lastname:"MARGARETA",name:" de Troancio"},
  {id:21, lastname:"MARGARETA",name:" de Ypra"},
  {id:22, lastname:"MARIA",name:" Alorie"},
  {id:23, lastname:"MARIA",name:" de Lingonis"},
];
