dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

addons:
  sonarcloud:
    organization: "vpo92-github"

jdk:
  - oraclejdk8
script:
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
