dist: trusty
sudo: required

language: node_js
node_js:
  - "node"
  - "11.10.1"
  - "12"

addons:
  sonarcloud:
    organization: "vpo92-github"

script:
  - npm test
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
