version: "3"

networks:
  public:
    external:
      name: public

services:
  studium_api:
    image: studium/api
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    links:
      - mongodb
      - studium_web
    depends_on:
      - mongodb
    restart: always
    networks:
     - default
     - public
    labels:
      - "traefik.frontend.rule=Host:studium-api.vincentpoupet.fr"
  studium_web:
    image: studium/web
    environment:
      - API_URL=http://studium-api.vincentpoupet.fr
    ports:
      - 3001:3001
    networks:
     - default
     - public
    labels:
      - "traefik.frontend.rule=Host:studium.vincentpoupet.fr"
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    networks:
     - default
    ports:
      - 27017:27017
  studium_admin:
    image: studium/admin
    environment:
      - API_URL=http://studium_api:3000
      - APPLICATION_URL=http://studium-admin.vincentpoupet.fr
      - APPLICATION_PATH=/
    ports:
      - 3002:80
    networks:
     - default
     - public
    labels:
      - "traefik.frontend.rule=Host:studium-admin.vincentpoupet.fr"
