
const dataLineTypes = {
  '1a': 'reference',
  '1b': 'name',
  '1c': 'nameVariant', //define type SimpleValueArray..
  '1d': 'shortDescription',
  '1e': 'datesOfLife',
  '1f': 'datesOfActivity',
  '1g': 'activityMediane',
  '1h': 'gender',
  '1k': 'status',
  '2a': 'birthPlace',
  '2b': 'diocese',
  '2c': 'movesInOutParis',
  '3a': 'socialClassOrigin',
  '3b': 'familyNetwork',
  '3c': 'personalSocialClass',
  '3d': 'personalServicesRelationship',
  '3e': 'friends',
  '3f': 'controversyOrDebates',
  '3g': 'connectionsWith',
  '3h': 'memberOfGroups',
  '3i': 'politicalRelationships',
  '3j': 'professionalRelationships',
  '3k': 'willExecutor',
  '3l': 'studentProfessorRelationships',
  '5a': 'preUniversity',
  '5b': 'university',
  '5c': 'grades',
  //no '5d': '',
  '5e': 'universityCollege',
  '5f': 'collegeFundations',
  '6a': 'ecclesiasticalStatus',
  '6b': 'secularPosition',
  '6c': 'benefits',
  '6d': 'regularOrder',
  '6f': 'regularFunctions',
  '6i': 'popFunctions',
  '6j': 'otherFunctions',
  '6k': 'communityFundations',
  '7a': 'professorOrPerceptor',
  '7b': 'universityFunction',
  '7c': 'lawFunction',
  '7d': 'propertiesAdministrator',
  '7e': 'townAdministrator',
  '7f': 'culturalFunction',
  '7g': 'kingdowChurchFunction',
  '7h': 'kingdomCulturalFunction',
  '7i': 'kingdomVariousFunction',
  '7j': 'royalAdministration',
  '7k': 'localAdministrationFunction',
  '7l': 'representation',
  '7m': 'business',
  '7n': 'medicine',
  '7o': 'otherJob',
  '8a': 'importantPosition',
  '8d': 'jailed',
  '8e': 'violentDeath',
  '8f': 'exil',
  '8g': 'justiceFacts',
  '9':  'travels',
  '10a': 'universityCommission',
  '10b': 'otherCommission',
  '11a': 'parisHousing',
  '11b': 'otherHousing',
  '12a': 'incomes',
  '13a': 'will',
  '14a': 'gifts',
  '15a': 'emblems',
  '15b': 'seals',
  '16a':'orality',
  '17a':'otherActivities',
  '18.1':'bookOwner',
  '19' : 'manyFields',
  '20' : 'religion',
  '21' : 'philosophy',
  '22' : 'philosophyExtended',
  '23' : 'science',
  '24' : 'medicineOpus',
  '25' : 'litterature',
  '26' : 'justice',
  '27' : 'pratical',
  '28' : 'musical',
  '30' : 'administrativePractice',
  '50' : 'history',
  '60' : 'political',
  '88' : 'discussedMusical',
  '89' : 'discussedManyFields',
  '90' : 'discussedReligion',
  '91' : 'discussedPhilosophy',
  '92' : 'discussedPhilosophyExtended',
  '94' : 'discussedMedicine',
  '93' : 'discussedScience',
  '95' : 'discussedLitterature',
  '96' : 'discussedJustice',
  '97' : 'discussedPratical',
  '98' : 'discussedHistory',
  '99' : 'discussedPolitical',
  '99s':'workSources',
  '99a':'workReferences',
  '99b':'bookReferences',
  '99c':'otherBases',
};


const opusLineTypes = {
  'a': 'title',
  'v' : 'titleVariant',
  'b' : 'dateAndPlace',
  'l' : 'language',
  'c' : 'manuscrits',
  'cc' : 'incipits',
  "ccc" : 'colophon',
  'd' : 'editionBefore1700',
  'e' : 'dedicaceOrAdress',
  'f' : 'editorialWork',
  'g' : 'versionWork',
  'i' : 'modernEdition',
  'j' : 'illustration',
  'k' : 'otherLanguage',
  "k1":		'latine'		,
  "k2":		'anglaise'		,
  "k3":		'allemande'		,
  "k4":		'française'		,
  "k5":		'hollandaise'		,
  "k6":		'italienne'		,
  "k7":		'espagnole'		,
  "k8":		'tchèque'		,
  "k9":		'gaélique'		,
  "k10":		'danoise'		,
  "k11":		'hongroise'		,
  "k12":		'galloise'		,
  "k13":		'provençale'		,
  "k14":		'polonaise'		,
  "k15":		'portugaise'		,
  "k16":		'suédoise'		,
  "k17":		'grecque'		,
  "k18":		'romanche'		,
  "k19":		'hébraïque'		,
  "k20":		'catalane'		,
  'm' : 'context',
  'n' : 'ISTC-GW',
};


export function getDataLineNameByCode(code){
  return dataLineTypes[code];
}

export function getOpusLineNameByCode(code){
  return opusLineTypes[code];
}

export function getVersionLineNameByCode(code){
  //Idem a OpusLine
  return getOpusLineNameByCode(code);
}
